### ISSUE TITLE
¿Cómo lo ejecuto?

### ISSUE THREAD

**Issue by iblancasa** [acasadoquijada/ETSIIT_BOT#1]
Quiero echar una mano en el proyecto, pero me es imposible ejecutarlo. 

He seguido los siguientes pasos:
- He clonado el repositorio
- He instalado la biblioteca `pip install pyTelegramBotAPI`
- He creado un fichero llamado "conf.py" con una variable llamada token y el token del bot que he creado para probar el bot
- He creado, en la raíz del repositorio, un directorio llamado "informacion" y, dentro de este, un fichero llamado "registro.txt"

No recibo error en la ejecución pero, si me voy a Telegram y le mando el comando "/start", me responde "Se ha producido un error, intentelo mas tarde".

¿Hay que instalar algo más? 

Gracias

**Comment by acasadoquijada** [comment]
Al hacer /start te abre un archivo `../informacion/start.txt` creo que te falta y por eso te salta el error.
Si quieres te puedo pasar un pantallazo de como tengo los ficheros organizados por privado

**Comment by iblancasa** [comment]
No... ni por esas.
He probado a descargar todo de nuevo y seguir todos los pasos. Esta vez me he saltado el paso de crear el directorio "informacion" y el resultado es el mismo.
Sigo probando

**Comment by iblancasa** [comment]
Ya he encontrado el problema...

Tienes un fichero para mostrar el mensaje después del "start"... Y no lo subes. Entonces, el bot revienta. 
¿Puedo hacer algunos "arreglillos"?
Una buena práctica sería separar todo en módulos: el del calendario, el de la web, el de... y así que pueda haber varia gente trabajando en módulos distintos sin "pisarse" entre ellos

**Comment by acasadoquijada** [comment]
No lo he subido para no "guarrear" el repositorio pero si quieres puedo subirlos.

Si si, justo ayer pense en separar todo en modulos, no hay problema, es mas te lo agradeceria bastante

**Comment by acasadoquijada** [comment]
He dividido el bot en módulos como me recomendaste, por lo que voy a cerrar este issue
